"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from slackspec import utils
from typing import Any, Optional


@dataclasses.dataclass
class AdminUsersInviteSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AdminUsersInviteApplicationJSON:
    
    channel_ids: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('channel_ids') }})
    r"""A comma-separated list of `channel_id`s for this user to join. At least one channel is required."""
    email: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('email') }})
    r"""The email address of the person to invite."""
    team_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('team_id') }})
    r"""The ID (`T1234`) of the workspace."""
    custom_message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('custom_message'), 'exclude': lambda f: f is None }})
    r"""An optional message to send to the user in the invite email."""
    guest_expiration_ts: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('guest_expiration_ts'), 'exclude': lambda f: f is None }})
    r"""Timestamp when guest account should be disabled. Only include this timestamp if you are inviting a guest user and you want their account to expire on a certain date."""
    is_restricted: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_restricted'), 'exclude': lambda f: f is None }})
    r"""Is this user a multi-channel guest user? (default: false)"""
    is_ultra_restricted: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_ultra_restricted'), 'exclude': lambda f: f is None }})
    r"""Is this user a single channel guest user? (default: false)"""
    real_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('real_name'), 'exclude': lambda f: f is None }})
    r"""Full name of the user."""
    resend: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resend'), 'exclude': lambda f: f is None }})
    r"""Allow this invite to be resent in the future if a user has not signed up yet. (default: false)"""
    

@dataclasses.dataclass
class AdminUsersInviteRequest:
    
    request_body: AdminUsersInviteApplicationJSON = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    token: str = dataclasses.field(metadata={'header': { 'field_name': 'token', 'style': 'simple', 'explode': False }})
    r"""Authentication token. Requires scope: `admin.users:write`"""
    

@dataclasses.dataclass
class AdminUsersInviteResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    default_error_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    default_success_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    