"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from slackspec import utils
from typing import Any, Optional


@dataclasses.dataclass
class AdminUsergroupsAddTeamsSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AdminUsergroupsAddTeamsApplicationJSON:
    
    team_ids: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('team_ids') }})
    r"""A comma separated list of encoded team (workspace) IDs. Each workspace *MUST* belong to the organization associated with the token."""
    usergroup_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('usergroup_id') }})
    r"""An encoded usergroup (IDP Group) ID."""
    auto_provision: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('auto_provision'), 'exclude': lambda f: f is None }})
    r"""When `true`, this method automatically creates new workspace accounts for the IDP group members."""
    

@dataclasses.dataclass
class AdminUsergroupsAddTeamsRequest:
    
    request_body: AdminUsergroupsAddTeamsApplicationJSON = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    token: str = dataclasses.field(metadata={'header': { 'field_name': 'token', 'style': 'simple', 'explode': False }})
    r"""Authentication token. Requires scope: `admin.teams:write`"""
    

@dataclasses.dataclass
class AdminUsergroupsAddTeamsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    default_error_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    default_success_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    