"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class AdminTeamsSettingsSetIconSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class AdminTeamsSettingsSetIconRequestBody:
    
    image_url: str = dataclasses.field(metadata={'form': { 'field_name': 'image_url' }})
    r"""Image URL for the icon"""
    team_id: str = dataclasses.field(metadata={'form': { 'field_name': 'team_id' }})
    r"""ID for the workspace to set the icon for."""
    token: str = dataclasses.field(metadata={'form': { 'field_name': 'token' }})
    r"""Authentication token. Requires scope: `admin.teams:write`"""
    

@dataclasses.dataclass
class AdminTeamsSettingsSetIconResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    default_error_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    default_success_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    