"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from slackspec import utils
from typing import Any, Optional


@dataclasses.dataclass
class AdminTeamsSettingsSetDiscoverabilitySecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AdminTeamsSettingsSetDiscoverabilityApplicationJSON:
    
    discoverability: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('discoverability') }})
    r"""This workspace's discovery setting. It must be set to one of `open`, `invite_only`, `closed`, or `unlisted`."""
    team_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('team_id') }})
    r"""The ID of the workspace to set discoverability on."""
    

@dataclasses.dataclass
class AdminTeamsSettingsSetDiscoverabilityRequest:
    
    request_body: AdminTeamsSettingsSetDiscoverabilityApplicationJSON = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    token: str = dataclasses.field(metadata={'header': { 'field_name': 'token', 'style': 'simple', 'explode': False }})
    r"""Authentication token. Requires scope: `admin.teams:write`"""
    

@dataclasses.dataclass
class AdminTeamsSettingsSetDiscoverabilityResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    default_error_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    default_success_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    