"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class APITestSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class APITestRequest:
    
    error: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'error', 'style': 'form', 'explode': True }})
    r"""Error response to return"""
    foo: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'foo', 'style': 'form', 'explode': True }})
    r"""example property to return"""
    

@dataclasses.dataclass
class APITestResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_test_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Artificial error response"""
    api_test_success_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Standard success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    