"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class AppsPermissionsInfoSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class AppsPermissionsInfoRequest:
    
    token: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `none`"""
    

@dataclasses.dataclass
class AppsPermissionsInfoResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    apps_permissions_info_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Standard failure response when used with an invalid token"""
    apps_permissions_info_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Standard success response when used with a user token"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    