"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class AuthRevokeSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class AuthRevokeRequest:
    
    token: str = dataclasses.field(metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `none`"""
    test: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'test', 'style': 'form', 'explode': True }})
    r"""Setting this parameter to `1` triggers a _testing mode_ where the specified token will not actually be revoked."""
    

@dataclasses.dataclass
class AuthRevokeResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    auth_revoke_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    auth_revoke_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    