"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class BotsInfoSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class BotsInfoRequest:
    
    token: str = dataclasses.field(metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `users:read`"""
    bot: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'bot', 'style': 'form', 'explode': True }})
    r"""Bot user to get info on"""
    

@dataclasses.dataclass
class BotsInfoResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    bots_info_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""When no bot can be found, it returns an error."""
    bots_info_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""When successful, returns bot info by bot ID."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    