"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class ConversationsRepliesSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class ConversationsRepliesRequest:
    
    channel: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'channel', 'style': 'form', 'explode': True }})
    r"""Conversation ID to fetch thread from."""
    cursor: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': True }})
    r"""Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first \\"page\\" of the collection. See [pagination](/docs/pagination) for more detail."""
    inclusive: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'inclusive', 'style': 'form', 'explode': True }})
    r"""Include messages with latest or oldest timestamp in results only when either timestamp is specified."""
    latest: Optional[float] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'latest', 'style': 'form', 'explode': True }})
    r"""End of time range of messages to include in results."""
    limit: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': True }})
    r"""The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the users list hasn't been reached."""
    oldest: Optional[float] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'oldest', 'style': 'form', 'explode': True }})
    r"""Start of time range of messages to include in results."""
    token: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `conversations:history`"""
    ts: Optional[float] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'ts', 'style': 'form', 'explode': True }})
    r"""Unique identifier of a thread's parent message. `ts` must be the timestamp of an existing message with 0 or more replies. If there are no replies then just the single message referenced by `ts` will return - it is just an ordinary, unthreaded message."""
    

@dataclasses.dataclass
class ConversationsRepliesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    conversations_replies_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    conversations_replies_success_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    