"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class DndSetSnoozeSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class DndSetSnoozeRequestBody:
    
    num_minutes: str = dataclasses.field(metadata={'form': { 'field_name': 'num_minutes' }})
    r"""Number of minutes, from now, to snooze until."""
    token: str = dataclasses.field(metadata={'form': { 'field_name': 'token' }})
    r"""Authentication token. Requires scope: `dnd:write`"""
    

@dataclasses.dataclass
class DndSetSnoozeResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    dnd_set_snooze_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    dnd_set_snooze_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    