"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class PinsListSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class PinsListRequest:
    
    channel: str = dataclasses.field(metadata={'query_param': { 'field_name': 'channel', 'style': 'form', 'explode': True }})
    r"""Channel to get pinned items for."""
    token: str = dataclasses.field(metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `pins:read`"""
    

@dataclasses.dataclass
class PinsListResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pins_list_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    pins_list_success_schema: Optional[dict[str, Any]] = dataclasses.field(default=None)
    r"""Typical success response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    