"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class UsergroupsUsersListSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class UsergroupsUsersListRequest:
    
    token: str = dataclasses.field(metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `usergroups:read`"""
    usergroup: str = dataclasses.field(metadata={'query_param': { 'field_name': 'usergroup', 'style': 'form', 'explode': True }})
    r"""The encoded ID of the User Group to update."""
    include_disabled: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'include_disabled', 'style': 'form', 'explode': True }})
    r"""Allow results that involve disabled User Groups."""
    

@dataclasses.dataclass
class UsergroupsUsersListResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    usergroups_users_list_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Standard failure response when used with an invalid token"""
    usergroups_users_list_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Standard success response when used with a user token"""
    