"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class UsergroupsListSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class UsergroupsListRequest:
    
    token: str = dataclasses.field(metadata={'query_param': { 'field_name': 'token', 'style': 'form', 'explode': True }})
    r"""Authentication token. Requires scope: `usergroups:read`"""
    include_count: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'include_count', 'style': 'form', 'explode': True }})
    r"""Include the number of users in each User Group."""
    include_disabled: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'include_disabled', 'style': 'form', 'explode': True }})
    r"""Include disabled User Groups."""
    include_users: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'include_users', 'style': 'form', 'explode': True }})
    r"""Include the list of users for each User Group."""
    

@dataclasses.dataclass
class UsergroupsListResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    usergroups_list_error_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response"""
    usergroups_list_schema: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response"""
    