"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional


@dataclasses.dataclass
class ViewsPushSecurity:
    
    slack_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'oauth2', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class ViewsPushRequest:
    
    token: str = dataclasses.field(metadata={'header': { 'field_name': 'token', 'style': 'simple', 'explode': False }})
    r"""Authentication token. Requires scope: `none`"""
    trigger_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'trigger_id', 'style': 'form', 'explode': True }})
    r"""Exchange a trigger to post to the user."""
    view: str = dataclasses.field(metadata={'query_param': { 'field_name': 'view', 'style': 'form', 'explode': True }})
    r"""A [view payload](/reference/surfaces/views). This must be a JSON-encoded string."""
    

@dataclasses.dataclass
class ViewsPushResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    default_error_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical error response."""
    default_success_template: Optional[dict[str, dict[str, Any]]] = dataclasses.field(default=None)
    r"""Typical success response includes the pushed view payload."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    