"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from slackspec.models import operations
from typing import Any, Optional

class AdminTeamsSettings:
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    
    def admin_teams_settings_info(self, request: operations.AdminTeamsSettingsInfoRequest, security: operations.AdminTeamsSettingsInfoSecurity) -> operations.AdminTeamsSettingsInfoResponse:
        r"""Fetch information about settings in a workspace
        https://api.slack.com/methods/admin.teams.settings.info - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/admin.teams.settings.info'
        
        headers = utils.get_headers(request)
        query_params = utils.get_query_params(operations.AdminTeamsSettingsInfoRequest, request)
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('GET', url, params=query_params, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.AdminTeamsSettingsInfoResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_success_template = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_error_template = out

        return res

    
    def admin_teams_settings_set_default_channels(self, request: operations.AdminTeamsSettingsSetDefaultChannelsRequestBody, security: operations.AdminTeamsSettingsSetDefaultChannelsSecurity) -> operations.AdminTeamsSettingsSetDefaultChannelsResponse:
        r"""Set the default channels of a workspace.
        https://api.slack.com/methods/admin.teams.settings.setDefaultChannels - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/admin.teams.settings.setDefaultChannels'
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request", 'form')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.AdminTeamsSettingsSetDefaultChannelsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_success_template = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_error_template = out

        return res

    
    def admin_teams_settings_set_description(self, request: operations.AdminTeamsSettingsSetDescriptionRequest, security: operations.AdminTeamsSettingsSetDescriptionSecurity) -> operations.AdminTeamsSettingsSetDescriptionResponse:
        r"""Set the description of a given workspace.
        https://api.slack.com/methods/admin.teams.settings.setDescription - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/admin.teams.settings.setDescription'
        
        headers = utils.get_headers(request)
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.AdminTeamsSettingsSetDescriptionResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_success_template = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_error_template = out

        return res

    
    def admin_teams_settings_set_discoverability(self, request: operations.AdminTeamsSettingsSetDiscoverabilityRequest, security: operations.AdminTeamsSettingsSetDiscoverabilitySecurity) -> operations.AdminTeamsSettingsSetDiscoverabilityResponse:
        r"""An API method that allows admins to set the discoverability of a given workspace
        https://api.slack.com/methods/admin.teams.settings.setDiscoverability - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/admin.teams.settings.setDiscoverability'
        
        headers = utils.get_headers(request)
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.AdminTeamsSettingsSetDiscoverabilityResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_success_template = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_error_template = out

        return res

    
    def admin_teams_settings_set_icon(self, request: operations.AdminTeamsSettingsSetIconRequestBody, security: operations.AdminTeamsSettingsSetIconSecurity) -> operations.AdminTeamsSettingsSetIconResponse:
        r"""Sets the icon of a workspace.
        https://api.slack.com/methods/admin.teams.settings.setIcon - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/admin.teams.settings.setIcon'
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request", 'form')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.AdminTeamsSettingsSetIconResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_success_template = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_error_template = out

        return res

    
    def admin_teams_settings_set_name(self, request: operations.AdminTeamsSettingsSetNameRequest, security: operations.AdminTeamsSettingsSetNameSecurity) -> operations.AdminTeamsSettingsSetNameResponse:
        r"""Set the name of a given workspace.
        https://api.slack.com/methods/admin.teams.settings.setName - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/admin.teams.settings.setName'
        
        headers = utils.get_headers(request)
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.AdminTeamsSettingsSetNameResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_success_template = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.default_error_template = out

        return res

    