"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from slackspec.models import operations
from typing import Any, Optional

class ChatScheduledMessages:
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    
    def chat_scheduled_messages_list(self, request: operations.ChatScheduledMessagesListRequest, security: operations.ChatScheduledMessagesListSecurity) -> operations.ChatScheduledMessagesListResponse:
        r"""Returns a list of scheduled messages.
        https://api.slack.com/methods/chat.scheduledMessages.list - API method documentation
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/chat.scheduledMessages.list'
        
        headers = utils.get_headers(request)
        query_params = utils.get_query_params(operations.ChatScheduledMessagesListRequest, request)
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('GET', url, params=query_params, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ChatScheduledMessagesListResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.chat_scheduled_messages_list_schema = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[dict[str, dict[str, Any]]])
                res.chat_scheduled_messages_list_error_schema = out

        return res

    